#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"

trigger-cron-entries() {
  local app schedule

  schedule="$(fn-plugin-property-get "$PLUGIN_COMMAND_PREFIX" "--global" "schedule")"
  if [[ -n "$schedule" ]]; then
    echo "$schedule;dokku ps:restart --all;/var/log/dokku/$PLUGIN_COMMAND_PREFIX.log"
  fi

  for app in $(dokku_apps "false" 2>/dev/null); do
    schedule="$(fn-plugin-property-get "$PLUGIN_COMMAND_PREFIX" "$APP" "schedule")"
    if [[ -n "$schedule" ]]; then
      echo "$schedule;dokku ps:restart $app;/var/log/dokku/$PLUGIN_COMMAND_PREFIX-$app.log"
    fi
  done
}

trigger-cron-entries "$@"
