#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-post-app-clone-setup() {
  declare desc="sets up properties for new app"
  declare trigger="post-app-clone-setup"
  declare OLD_APP="$1" NEW_APP="$2"

  fn-plugin-property-clone "$PLUGIN_COMMAND_PREFIX" "$OLD_APP" "$NEW_APP"
}

trigger-post-app-clone-setup "$@"
