#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-post-delete() {
  declare desc="destroys the $PLUGIN_COMMAND_PREFIX properties for a given app"
  declare trigger="post-delete"
  declare APP="$1"

  fn-plugin-property-destroy "$PLUGIN_COMMAND_PREFIX" "$APP"
}

trigger-post-delete "$@"
