#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
source "$PLUGIN_AVAILABLE_PATH/$PLUGIN_COMMAND_PREFIX/report-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-report-single "$@"
