#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
if [[ -f "$PLUGIN_AVAILABLE_PATH/$PLUGIN_COMMAND_PREFIX/property-functions" ]]; then
  source "$PLUGIN_AVAILABLE_PATH/$PLUGIN_COMMAND_PREFIX/property-functions"
fi

cmd-report() {
  declare desc="displays a $PLUGIN_COMMAND_PREFIX report for one or more apps"
  declare cmd="$PLUGIN_COMMAND_PREFIX:report"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1" INFO_FLAG="$2"
  local INSTALLED_APPS

  if [[ -n "$APP" ]] && [[ "$APP" == --* ]]; then
    INFO_FLAG="$APP"
    APP=""
  fi

  if [[ -z "$APP" ]] && [[ -z "$INFO_FLAG" ]]; then
    INFO_FLAG="true"
  fi

  if [[ -z "$APP" ]]; then
    INSTALLED_APPS=$(dokku_apps)
    for app in $INSTALLED_APPS; do
      cmd-report-single "$app" "$INFO_FLAG" | tee || true
    done
  else
    cmd-report-single "$APP" "$INFO_FLAG"
  fi
}

cmd-report-single() {
  declare APP="$1" INFO_FLAG="$2"
  if [[ "$INFO_FLAG" == "true" ]]; then
    INFO_FLAG=""
  fi
  verify_app_name "$APP"
  declare -a flag_map
  declare -F | grep "fn-report-$PLUGIN_COMMAND_PREFIX" | while IFS= read -r line; do
    local fn_name="$(echo "$line" | cut -d' ' -f3)"
    flag_map+=("--$PLUGIN_COMMAND_PREFIX-${fn_name#"fn-report-$PLUGIN_COMMAND_PREFIX-"}: $("$fn_name" "$APP")")
  done

  if [[ -z "$INFO_FLAG" ]]; then
    dokku_log_info2_quiet "${APP} $PLUGIN_COMMAND_PREFIX information"
    for flag in "${flag_map[@]}"; do
      key="$(echo "${flag#--}" | cut -f1 -d' ' | tr - ' ')"
      dokku_log_verbose "$(printf "%-30s %-25s" "${key^}" "${flag#*: }")"
    done
  else
    local match=false
    local value_exists=false
    for flag in "${flag_map[@]}"; do
      valid_flags="${valid_flags} $(echo "$flag" | cut -d':' -f1)"
      if [[ "$flag" == "${INFO_FLAG}:"* ]]; then
        value=${flag#*: }
        size="${#value}"
        if [[ "$size" -ne 0 ]]; then
          echo "$value" && match=true && value_exists=true
        else
          match=true
        fi
      fi
    done
    [[ "$match" == "true" ]] || dokku_log_fail "Invalid flag passed, valid flags:${valid_flags}"
    [[ "$value_exists" == "true" ]] || dokku_log_fail "not deployed"
  fi
}
