#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

subcommand-show-config() {
  #E shows the generated cron config
  #E dokku $PLUGIN_COMMAND_PREFIX:show-config
  declare desc="show the generated config"
  declare cmd="$PLUGIN_COMMAND_PREFIX:show-config"
  [[ "$1" == "$cmd" ]] && shift 1

  crontab -l | sed -e '/^$/,$d'
  crontab -l | grep "/cron-restart"
}

subcommand-show-config "$@"
