#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

subcommand-show-config() {
  declare desc="Shows the generated crontab config relevant to $PLUGIN_COMMAND_PREFIX"
  declare cmd="$PLUGIN_COMMAND_PREFIX:show-config"
  [[ "$1" == "$cmd" ]] && shift 1

  crontab -l | sed -e '/^$/,$d'
  echo ""
  crontab -l | grep "/cron-restart"
}

subcommand-show-config "$@"
